"""
Unit tests for database models.

These tests verify model instantiation, relationships, constraints, and
string representations. They test models in-memory without requiring a
database connection.
"""

import uuid
from datetime import datetime, timezone

import pytest

from app.models import OAuthProvider, ProviderType, Tenant, User


class TestTenantModel:
    """Test suite for the Tenant model."""

    def test_tenant_creation(self):
        """Test basic tenant instantiation with required fields."""
        tenant = Tenant(
            slug="acme-corp",
            name="Acme Corporation",
            settings={"theme": "dark", "language": "en"},
        )

        assert tenant.slug == "acme-corp"
        assert tenant.name == "Acme Corporation"
        assert tenant.settings == {"theme": "dark", "language": "en"}
        assert tenant.is_active is True

    def test_tenant_default_id_is_uuid(self):
        """Test that tenant ID is automatically generated as UUID."""
        tenant = Tenant(slug="test", name="Test")

        # ID should be None until committed to database, or generated by default
        # Since we have default=uuid.uuid4, it should be generated
        assert isinstance(tenant.id, uuid.UUID)

    def test_tenant_explicit_id(self):
        """Test that tenant can be created with explicit UUID."""
        tenant_id = uuid.uuid4()
        tenant = Tenant(id=tenant_id, slug="test", name="Test")

        assert tenant.id == tenant_id

    def test_tenant_default_settings(self):
        """Test that settings defaults to empty dict."""
        tenant = Tenant(slug="test", name="Test")

        assert tenant.settings == {}

    def test_tenant_default_is_active(self):
        """Test that is_active defaults to True."""
        tenant = Tenant(slug="test", name="Test")

        assert tenant.is_active is True

    def test_tenant_repr(self):
        """Test tenant string representation."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")

        assert repr(tenant) == "<Tenant acme-corp>"


class TestUserModel:
    """Test suite for the User model."""

    def test_user_creation(self):
        """Test basic user instantiation with required fields."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        user = User(
            tenant=tenant,
            oauth_subject="google|12345",
            email="user@acme.com",
            display_name="John Doe",
        )

        assert user.oauth_subject == "google|12345"
        assert user.email == "user@acme.com"
        assert user.display_name == "John Doe"
        assert user.is_active is True

    def test_user_default_id_is_uuid(self):
        """Test that user ID is automatically generated as UUID."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        user = User(tenant=tenant, oauth_subject="google|12345", email="user@acme.com")

        assert isinstance(user.id, uuid.UUID)

    def test_user_explicit_id(self):
        """Test that user can be created with explicit UUID."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        user_id = uuid.uuid4()
        user = User(
            id=user_id,
            tenant=tenant,
            oauth_subject="google|12345",
            email="user@acme.com",
        )

        assert user.id == user_id

    def test_user_tenant_relationship_forward(self):
        """Test forward relationship from user to tenant."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        user = User(tenant=tenant, oauth_subject="google|12345", email="user@acme.com")

        assert user.tenant == tenant

    def test_user_tenant_relationship_backward(self):
        """Test backward relationship from tenant to users."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        user1 = User(tenant=tenant, oauth_subject="google|12345", email="user1@acme.com")
        user2 = User(tenant=tenant, oauth_subject="google|67890", email="user2@acme.com")

        assert user1 in tenant.users
        assert user2 in tenant.users
        assert len(tenant.users) == 2

    def test_user_optional_display_name(self):
        """Test that display_name is optional."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        user = User(tenant=tenant, oauth_subject="google|12345", email="user@acme.com")

        assert user.display_name is None

    def test_user_default_is_active(self):
        """Test that is_active defaults to True."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        user = User(tenant=tenant, oauth_subject="google|12345", email="user@acme.com")

        assert user.is_active is True

    def test_user_repr(self):
        """Test user string representation."""
        tenant_id = uuid.uuid4()
        tenant = Tenant(id=tenant_id, slug="acme-corp", name="Acme Corporation")
        # Set tenant_id explicitly to test __repr__ (relationship doesn't populate FK in-memory)
        user = User(
            tenant_id=tenant_id,
            tenant=tenant,
            oauth_subject="google|12345",
            email="user@acme.com",
        )

        assert repr(user) == f"<User user@acme.com (tenant: {tenant_id})>"


class TestOAuthProviderModel:
    """Test suite for the OAuthProvider model."""

    def test_oauth_provider_creation(self):
        """Test basic OAuth provider instantiation with required fields."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        provider = OAuthProvider(
            tenant=tenant,
            provider_type=ProviderType.KEYCLOAK,
            issuer="http://keycloak:8080/realms/knowledge-mapper-dev",
            client_id="knowledge-mapper-backend",
            client_secret="secret123",
            jwks_uri="http://keycloak:8080/realms/knowledge-mapper-dev/protocol/openid-connect/certs",
        )

        assert provider.provider_type == ProviderType.KEYCLOAK
        assert provider.issuer == "http://keycloak:8080/realms/knowledge-mapper-dev"
        assert provider.client_id == "knowledge-mapper-backend"
        assert provider.client_secret == "secret123"
        assert provider.jwks_uri == "http://keycloak:8080/realms/knowledge-mapper-dev/protocol/openid-connect/certs"
        assert provider.is_active is True

    def test_oauth_provider_tenant_relationship_forward(self):
        """Test forward relationship from provider to tenant."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        provider = OAuthProvider(
            tenant=tenant,
            provider_type=ProviderType.KEYCLOAK,
            issuer="http://keycloak:8080/realms/knowledge-mapper-dev",
            client_id="knowledge-mapper-backend",
            jwks_uri="http://keycloak:8080/realms/knowledge-mapper-dev/protocol/openid-connect/certs",
        )

        assert provider.tenant == tenant

    def test_oauth_provider_tenant_relationship_backward(self):
        """Test backward relationship from tenant to OAuth providers."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        provider = OAuthProvider(
            tenant=tenant,
            provider_type=ProviderType.KEYCLOAK,
            issuer="http://keycloak:8080/realms/knowledge-mapper-dev",
            client_id="knowledge-mapper-backend",
            jwks_uri="http://keycloak:8080/realms/knowledge-mapper-dev/protocol/openid-connect/certs",
        )

        assert provider in tenant.oauth_providers
        assert len(tenant.oauth_providers) == 1

    def test_oauth_provider_optional_endpoints(self):
        """Test that endpoint fields are optional."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        provider = OAuthProvider(
            tenant=tenant,
            provider_type=ProviderType.KEYCLOAK,
            issuer="http://keycloak:8080/realms/knowledge-mapper-dev",
            client_id="knowledge-mapper-backend",
            jwks_uri="http://keycloak:8080/realms/knowledge-mapper-dev/protocol/openid-connect/certs",
        )

        assert provider.client_secret is None
        assert provider.authorization_endpoint is None
        assert provider.token_endpoint is None
        assert provider.userinfo_endpoint is None
        assert provider.discovery_endpoint is None

    def test_oauth_provider_with_all_endpoints(self):
        """Test OAuth provider with all optional endpoints set."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        provider = OAuthProvider(
            tenant=tenant,
            provider_type=ProviderType.AZURE_AD,
            issuer="https://login.microsoftonline.com/tenant-id/v2.0",
            client_id="azure-client-id",
            client_secret="azure-secret",
            jwks_uri="https://login.microsoftonline.com/tenant-id/discovery/v2.0/keys",
            authorization_endpoint="https://login.microsoftonline.com/tenant-id/oauth2/v2.0/authorize",
            token_endpoint="https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token",
            userinfo_endpoint="https://graph.microsoft.com/oidc/userinfo",
            discovery_endpoint="https://login.microsoftonline.com/tenant-id/v2.0/.well-known/openid-configuration",
        )

        assert provider.client_secret == "azure-secret"
        assert provider.authorization_endpoint == "https://login.microsoftonline.com/tenant-id/oauth2/v2.0/authorize"
        assert provider.token_endpoint == "https://login.microsoftonline.com/tenant-id/oauth2/v2.0/token"
        assert provider.userinfo_endpoint == "https://graph.microsoft.com/oidc/userinfo"
        assert provider.discovery_endpoint == "https://login.microsoftonline.com/tenant-id/v2.0/.well-known/openid-configuration"

    def test_oauth_provider_default_is_active(self):
        """Test that is_active defaults to True."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        provider = OAuthProvider(
            tenant=tenant,
            provider_type=ProviderType.KEYCLOAK,
            issuer="http://keycloak:8080/realms/knowledge-mapper-dev",
            client_id="knowledge-mapper-backend",
            jwks_uri="http://keycloak:8080/realms/knowledge-mapper-dev/protocol/openid-connect/certs",
        )

        assert provider.is_active is True

    def test_oauth_provider_repr(self):
        """Test OAuth provider string representation."""
        tenant_id = uuid.uuid4()
        tenant = Tenant(id=tenant_id, slug="acme-corp", name="Acme Corporation")
        # Set tenant_id explicitly to test __repr__ (relationship doesn't populate FK in-memory)
        provider = OAuthProvider(
            tenant_id=tenant_id,
            tenant=tenant,
            provider_type=ProviderType.KEYCLOAK,
            issuer="http://keycloak:8080/realms/knowledge-mapper-dev",
            client_id="knowledge-mapper-backend",
            jwks_uri="http://keycloak:8080/realms/knowledge-mapper-dev/protocol/openid-connect/certs",
        )

        assert repr(provider) == f"<OAuthProvider keycloak for tenant {tenant_id}>"


class TestProviderTypeEnum:
    """Test suite for the ProviderType enum."""

    def test_provider_type_values(self):
        """Test all provider type enum values."""
        assert ProviderType.KEYCLOAK.value == "keycloak"
        assert ProviderType.AZURE_AD.value == "azure_ad"
        assert ProviderType.OKTA.value == "okta"
        assert ProviderType.GOOGLE.value == "google"
        assert ProviderType.CUSTOM.value == "custom"

    def test_provider_type_from_string(self):
        """Test creating enum from string value."""
        assert ProviderType("keycloak") == ProviderType.KEYCLOAK
        assert ProviderType("azure_ad") == ProviderType.AZURE_AD
        assert ProviderType("okta") == ProviderType.OKTA
        assert ProviderType("google") == ProviderType.GOOGLE
        assert ProviderType("custom") == ProviderType.CUSTOM

    def test_provider_type_invalid_value(self):
        """Test that invalid provider type raises ValueError."""
        with pytest.raises(ValueError):
            ProviderType("invalid_provider")

    def test_provider_type_is_string(self):
        """Test that ProviderType enum is also a string."""
        provider_type = ProviderType.KEYCLOAK
        assert isinstance(provider_type, str)
        assert provider_type == "keycloak"


class TestModelRelationships:
    """Test suite for model relationships and cascade behavior."""

    def test_tenant_users_relationship(self):
        """Test tenant to users relationship."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        user1 = User(tenant=tenant, oauth_subject="google|1", email="user1@acme.com")
        user2 = User(tenant=tenant, oauth_subject="google|2", email="user2@acme.com")

        # Test forward references
        assert user1.tenant == tenant
        assert user2.tenant == tenant

        # Test backward reference
        assert user1 in tenant.users
        assert user2 in tenant.users
        assert len(tenant.users) == 2

    def test_tenant_oauth_providers_relationship(self):
        """Test tenant to OAuth providers relationship."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        provider = OAuthProvider(
            tenant=tenant,
            provider_type=ProviderType.KEYCLOAK,
            issuer="http://keycloak:8080/realms/knowledge-mapper-dev",
            client_id="knowledge-mapper-backend",
            jwks_uri="http://keycloak:8080/realms/knowledge-mapper-dev/protocol/openid-connect/certs",
        )

        # Test forward reference
        assert provider.tenant == tenant

        # Test backward reference
        assert provider in tenant.oauth_providers
        assert len(tenant.oauth_providers) == 1

    def test_multiple_users_same_tenant(self):
        """Test multiple users can belong to the same tenant."""
        tenant = Tenant(slug="acme-corp", name="Acme Corporation")
        users = [
            User(tenant=tenant, oauth_subject=f"google|{i}", email=f"user{i}@acme.com")
            for i in range(5)
        ]

        assert len(tenant.users) == 5
        for user in users:
            assert user.tenant == tenant
            assert user in tenant.users

    def test_same_oauth_subject_different_tenants(self):
        """Test that same OAuth subject can exist in different tenants."""
        tenant1 = Tenant(slug="acme-corp", name="Acme Corporation")
        tenant2 = Tenant(slug="contoso-ltd", name="Contoso Ltd")

        # Same OAuth subject (e.g., Google account) in different tenants
        user1 = User(tenant=tenant1, oauth_subject="google|12345", email="user@gmail.com")
        user2 = User(tenant=tenant2, oauth_subject="google|12345", email="user@gmail.com")

        assert user1.oauth_subject == user2.oauth_subject
        assert user1.tenant != user2.tenant
        assert user1.tenant == tenant1
        assert user2.tenant == tenant2


class TestModelImports:
    """Test suite for model imports."""

    def test_import_from_models_package(self):
        """Test that all models can be imported from app.models."""
        from app.models import OAuthProvider, ProviderType, Tenant, User

        assert Tenant is not None
        assert User is not None
        assert OAuthProvider is not None
        assert ProviderType is not None

    def test_import_specific_models(self):
        """Test importing individual models."""
        from app.models.oauth_provider import OAuthProvider, ProviderType
        from app.models.tenant import Tenant
        from app.models.user import User

        assert Tenant is not None
        assert User is not None
        assert OAuthProvider is not None
        assert ProviderType is not None
