"""Initial schema with tenants, users, oauth_providers and RLS policies

Revision ID: e10757622a70
Revises: 
Create Date: 2025-11-16 20:28:03.006310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e10757622a70'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade database schema.

    This function applies the forward migration, creating or modifying
    database objects to move the schema to the new version.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key for security and distributed ID generation'),
    sa.Column('slug', sa.String(length=255), nullable=False, comment="URL-safe identifier for tenant (e.g., 'acme-corp')"),
    sa.Column('name', sa.String(length=255), nullable=False, comment="Display name for tenant (e.g., 'Acme Corporation')"),
    sa.Column('settings', sa.JSON(), nullable=False, comment='Tenant-specific configuration as JSON'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag (False = deleted but preserved)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), nullable=False, comment='Integer primary key (internal use only)'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant this provider belongs to (unique)'),
    sa.Column('provider_type', sa.Enum('KEYCLOAK', 'AZURE_AD', 'OKTA', 'GOOGLE', 'CUSTOM', name='provider_type'), nullable=False, comment='Type of OAuth provider'),
    sa.Column('issuer', sa.String(length=500), nullable=False, comment='OAuth issuer URL (iss claim)'),
    sa.Column('client_id', sa.String(length=255), nullable=False, comment='OAuth client ID'),
    sa.Column('client_secret', sa.String(length=500), nullable=True, comment='OAuth client secret (encrypted in production)'),
    sa.Column('jwks_uri', sa.String(length=500), nullable=False, comment='JWKS endpoint URL for token validation'),
    sa.Column('authorization_endpoint', sa.String(length=500), nullable=True, comment='OAuth authorization endpoint'),
    sa.Column('token_endpoint', sa.String(length=500), nullable=True, comment='OAuth token endpoint'),
    sa.Column('userinfo_endpoint', sa.String(length=500), nullable=True, comment='OAuth userinfo endpoint'),
    sa.Column('discovery_endpoint', sa.String(length=500), nullable=True, comment='OIDC discovery endpoint (/.well-known/openid-configuration)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag (False = deleted but preserved)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_providers_id'), 'oauth_providers', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_providers_tenant_id'), 'oauth_providers', ['tenant_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID primary key for security and distributed ID generation'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant this user belongs to'),
    sa.Column('oauth_subject', sa.String(length=255), nullable=False, comment='Subject claim from OAuth token (sub)'),
    sa.Column('email', sa.String(length=255), nullable=False, comment="User's email address"),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='Optional display name for user'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete flag (False = deleted but preserved)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'oauth_subject', name='uq_tenant_oauth_subject')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_oauth_subject'), 'users', ['oauth_subject'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)

    # Enable Row-Level Security (RLS) on tenant-scoped tables
    # RLS is the primary security mechanism for tenant isolation
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE oauth_providers ENABLE ROW LEVEL SECURITY")

    # Create RLS policies for users table
    # Policy: Users can only see/modify users in their own tenant
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON users
        USING (tenant_id = COALESCE(
            NULLIF(current_setting('app.current_tenant_id', TRUE), '')::UUID,
            '00000000-0000-0000-0000-000000000000'::UUID
        ))
    """)

    # Create RLS policies for oauth_providers table
    # Policy: OAuth providers can only be accessed by their tenant
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON oauth_providers
        USING (tenant_id = COALESCE(
            NULLIF(current_setting('app.current_tenant_id', TRUE), '')::UUID,
            '00000000-0000-0000-0000-000000000000'::UUID
        ))
    """)

    # Note: Tenants table does not have RLS enabled
    # Tenant lookup needs to work before context is set (for subdomain resolution)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade database schema.

    This function applies the reverse migration, undoing the changes
    made in upgrade() to return the schema to the previous version.

    Important: Downgrades should be tested to ensure data safety.
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop RLS policies before dropping tables
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON oauth_providers")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON users")

    # Disable RLS on tables
    op.execute("ALTER TABLE oauth_providers DISABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE users DISABLE ROW LEVEL SECURITY")

    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_subject'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_oauth_providers_tenant_id'), table_name='oauth_providers')
    op.drop_index(op.f('ix_oauth_providers_id'), table_name='oauth_providers')
    op.drop_table('oauth_providers')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
